<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.74.3" />


<title>Analysis: Indiana COVID-19 Infection Rate Disparities - Jack&#39;s Blog</title>
<meta property="og:title" content="Analysis: Indiana COVID-19 Infection Rate Disparities - Jack&#39;s Blog">
<meta property="og:description" content="Some Hoosier demographics face disparity in COVID-19 infection rate">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  
  <meta property="description" content="Some Hoosier demographics face disparity in COVID-19 infection rate">
  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



<meta name="twitter:creator" content="@VanSchaikJack">
<meta name="twitter:site" content="@VanSchaikJack">


  
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="https://web.jackv.xyz/images/plot_2.png" >
  

  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/images/plot_3.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/jackvanschaik">GitHub</a></li>
    
    <li><a href="https://twitter.com/VanschaikJack">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">9 min read</span>
    

    <h1 class="article-title">Analysis: Indiana COVID-19 Infection Rate Disparities</h1>

    
    <span class="article-date">2020-10-09</span>
    

    <div class="article-content">
      
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="/rmarkdown-libs/datatables-css/datatables-crosstalk.css" rel="stylesheet" />
<script src="/rmarkdown-libs/datatables-binding/datatables.js"></script>
<link href="/rmarkdown-libs/dt-core/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="/rmarkdown-libs/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="/rmarkdown-libs/dt-core/js/jquery.dataTables.min.js"></script>
<link href="/rmarkdown-libs/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="/rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>


<pre class="r"><code>library(tidyverse)
library(corrplot)</code></pre>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>The following analysis shows a strong relationship between eviction in Indiana, African American population rate, and COVID infection rates. These populations are at an increased risk of a faster COVID-19 infection rate in Indiana.</p>
<p>This analysis is completely reproducible. The R code to gather the data, prep it, and perform the analysis are on my <a href="https://github.com/jackvanschaik/jackvblog/blob/master/content/post/2020-10-09-Indiana_COVID_and_evictions.Rmd">Github</a>.</p>
</div>
<div id="data-extract" class="section level2">
<h2>Data Extract</h2>
<p>We’ll extract data from two places:</p>
<ul>
<li><a href="https://www.coronavirus.in.gov/2393.htm">Indiana State Department of Health</a></li>
<li><a href="https://evictionlab.org/">Eviction Lab</a></li>
</ul>
<div id="isdh" class="section level4">
<h4>ISDH</h4>
<p>We’ll use ISDH’s county trends data from the MPH data hub.</p>
<pre class="r"><code>mph_to_df &lt;- function(resource_id) {
    url &lt;- sprintf(&quot;https://hub.mph.in.gov/api/3/action/datastore_search?resource_id=%s&amp;limit=1000000&quot;, resource_id)
    res &lt;- jsonlite::fromJSON(url)$result
    janitor::clean_names(res$records)
}

county_trends &lt;- mph_to_df(&quot;afaa225d-ac4e-4e80-9190-f6800c366b58&quot;)
county_trends %&gt;%
    mutate(
        county=as.character(location_id),
        date = as.Date(substr(date, 1, 10))
    ) -&gt;
    county_trends</code></pre>
</div>
<div id="eviction-lab" class="section level4">
<h4>Eviction Lab</h4>
<p>Data from the eviction lab is available for direct download. The most recent data available is from 2016.</p>
<pre class="r"><code>eviction &lt;- read_csv(&quot;https://eviction-lab-data-downloads.s3.amazonaws.com/IN/counties.csv&quot;)

eviction %&gt;%
    janitor::clean_names() %&gt;%
    filter(year == 2016) %&gt;%
    transmute(
        county = substr(as.character(geoid), 1, 5),
        population, 
        poverty_rate,
        pct_renter_occupied,
        median_gross_rent, 
        median_household_income,
        median_property_value,
        rent_burden,
        pct_white,
        pct_af_am,
        pct_hispanic,
        eviction_rate,
        eviction_filing_rate
    ) -&gt;
    eviction_2</code></pre>
</div>
</div>
<div id="data-transformation" class="section level2">
<h2>Data Transformation</h2>
<div id="cumulative-case-rate" class="section level4">
<h4>Cumulative Case Rate</h4>
<p>We want a metric to assess the spread in the pandemic over time. Here’s what we’ll do:</p>
<ul>
<li>Calculate the cumulative cases over time for each county</li>
<li>Divide cumulative cases by population</li>
<li>Find the line of best fit for each curve</li>
<li>Use the slope of that line to estimate infection growth rate</li>
</ul>
<p>The outlying line is Cass county. It had a huge outbreak in the first wave. We’ll exclude it from the analysis from here on out.</p>
<pre class="r"><code>eviction_2 %&gt;%
    select(county, population) %&gt;%
    inner_join(county_trends, by=&quot;county&quot;) %&gt;%
    mutate(date_number = as.numeric(date) - min(as.numeric(date))) %&gt;%
    arrange(county, date) %&gt;%
    group_by(county, county_name) %&gt;%
    mutate(case_rate = cumsum(covid_count)/population) -&gt;
    cum_case_1

ggplot(cum_case_1, aes(x = date, y=case_rate, color=county)) + 
    geom_line() +
    labs(x=&quot;Date&quot;, y=&quot;Cumulative Cases Per Population&quot;, title = &quot;Cumulative Case Rate for Indiana Counties&quot;) +
    theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/post/2020-10-09-Indiana_COVID_and_evictions_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>cum_case_1 %&gt;%
    filter(county != 18017) %&gt;%
    nest(X = !county) %&gt;%
    mutate(
        B1 = map(X, ~ lm(case_rate ~ date_number, data=.x)$coefficients[2])
    ) %&gt;%
    select(-X) %&gt;%
    unnest(cols = c(B1)) %&gt;%
    rename(avg_rate = B1) -&gt;
    county_rates</code></pre>
<p>Join this back to eviction data…</p>
<pre class="r"><code>county_rates %&gt;%
    inner_join(eviction_2, by=&quot;county&quot;) %&gt;%
    ungroup -&gt;
    eviction_3</code></pre>
</div>
<div id="variable-selection" class="section level4">
<h4>Variable Selection</h4>
<p>We’ll look for correlated predictors and remove any that are highly correlated.</p>
<pre class="r"><code>eviction_3 %&gt;%
    select(-county) %&gt;%
    filter(!is.na(eviction_rate)) %&gt;%
    cor %&gt;%
    corrplot</code></pre>
<p><img src="/post/2020-10-09-Indiana_COVID_and_evictions_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Household income. median rent, and property value are highly correlated. As one might expected, rate and ethnicity demographics are inversely correlated. Eviction rate and filing rate are highly correlated. Population count itself is not that informative. Percent renter occupied is correlated with rent burden. Based on all that, we’ll remove a few variables.</p>
<p>Also there’s</p>
<pre class="r"><code>sum(is.na(eviction_3$eviction_rate))</code></pre>
<pre><code>## [1] 8</code></pre>
<p>Rows with missing eviction data that we’ll remove.</p>
<pre class="r"><code>eviction_3 %&gt;%
    filter(!is.na(eviction_rate)) %&gt;%
    select(county, avg_rate, median_gross_rent, pct_af_am, eviction_rate, pct_renter_occupied) -&gt;
    eviction_4</code></pre>
</div>
</div>
<div id="analyze" class="section level2">
<h2>Analyze</h2>
<p>Now that the data is ready, we can do the actual analysis</p>
<div id="plots" class="section level4">
<h4>Plots</h4>
<p>Let’s look at some preliminary plots of predictors vs our rate variable</p>
<pre class="r"><code>gridExtra::grid.arrange(
    ggplot(eviction_4, aes(x=median_gross_rent, y=avg_rate)) + geom_point(),
    ggplot(eviction_4, aes(x=log(pct_af_am), y=avg_rate)) + geom_point(),
    ggplot(eviction_4, aes(x=eviction_rate, y=avg_rate)) + geom_point(),
    ggplot(eviction_4, aes(x=pct_renter_occupied, y=avg_rate)) + geom_point(),
    nrow = 2
)</code></pre>
<p><img src="/post/2020-10-09-Indiana_COVID_and_evictions_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>I ended up taking the log transform of <code>pct_af_am</code> to better meet the assumptions of a linear model.</p>
</div>
<div id="running-the-linear-model" class="section level4">
<h4>Running the Linear Model</h4>
<p>Now we can run our model</p>
<pre class="r"><code>fit_1 &lt;- lm(avg_rate ~ median_gross_rent + log(pct_af_am) + eviction_rate + pct_renter_occupied, 
            data = eviction_4)

summary(fit_1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = avg_rate ~ median_gross_rent + log(pct_af_am) + 
##     eviction_rate + pct_renter_occupied, data = eviction_4)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -3.848e-05 -1.597e-05 -3.806e-06  1.043e-05  8.967e-05 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)         3.992e-05  2.578e-05   1.549   0.1255  
## median_gross_rent   2.271e-08  3.293e-08   0.690   0.4924  
## log(pct_af_am)      4.050e-06  2.617e-06   1.548   0.1257  
## eviction_rate       3.222e-06  1.424e-06   2.263   0.0264 *
## pct_renter_occupied 2.511e-07  5.529e-07   0.454   0.6510  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.407e-05 on 78 degrees of freedom
## Multiple R-squared:  0.1928, Adjusted R-squared:  0.1514 
## F-statistic: 4.658 on 4 and 78 DF,  p-value: 0.002007</code></pre>
<p>This p values are telling me that percent African American and Eviction rate are most likely the only significant variables.</p>
<pre class="r"><code>fit_2 &lt;- lm(avg_rate ~ log(pct_af_am) + eviction_rate, data = eviction_4)

summary(fit_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = avg_rate ~ log(pct_af_am) + eviction_rate, data = eviction_4)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -3.889e-05 -1.663e-05 -2.060e-06  1.143e-05  8.907e-05 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    6.158e-05  3.916e-06  15.722   &lt;2e-16 ***
## log(pct_af_am) 5.161e-06  2.091e-06   2.469   0.0157 *  
## eviction_rate  3.370e-06  1.393e-06   2.420   0.0178 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.388e-05 on 80 degrees of freedom
## Multiple R-squared:  0.1853, Adjusted R-squared:  0.1649 
## F-statistic: 9.098 on 2 and 80 DF,  p-value: 0.0002753</code></pre>
</div>
<div id="checking-the-fit" class="section level4">
<h4>Checking the fit</h4>
<p>Finally, we should check the fit of our model by checking the normality of our variables. We can do this by looking at the quantile plot:</p>
<pre class="r"><code>qqnorm(fit_2$residuals)
qqline(y=fit_2$residuals)</code></pre>
<p><img src="/post/2020-10-09-Indiana_COVID_and_evictions_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The residuals are pretty normal, so we meet that assumption.</p>
<pre class="r"><code>cor(fit_2$residuals, eviction_4$avg_rate)</code></pre>
<pre><code>## [1] 0.9026065</code></pre>
<pre class="r"><code>cor(fit_2$residuals, eviction_4$avg_rate, method = &quot;spearman&quot;)</code></pre>
<pre><code>## [1] 0.8656857</code></pre>
<pre class="r"><code>plot(y=fit_2$residuals, x=eviction_4$avg_rate)</code></pre>
<p><img src="/post/2020-10-09-Indiana_COVID_and_evictions_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Our residuals are highly correlated. This essentially tells us that as the average infection rate gets larger, the model’s guess get farther off. This doesn’t matter as much in our use case because we’re not trying to do prediction. We also would probably be able to account for this relationship if we had other variables.</p>
</div>
<div id="discussion" class="section level4">
<h4>Discussion</h4>
<p>The R-squared values for our model is about 0.15– meaning 15% of the variation in infection rate can be explained by eviction rate and percent African American. There are of course many other factors that determine infection rate, but we did in fact find our two predictor variables to be statistically significant. The eviction rate and percent African American population is in fact associated with an increased infection rate.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Here are the key takeaways:</p>
<ul>
<li>Analyzed 83 Indiana counties using 2 datasets</li>
<li>Outcome of interest was the infection rate of Indiana counties</li>
<li>Several variables were narrowed down to two with significance</li>
<li>Increased COVID infection rate was significantly associated with an increased African American population rate in a county (p = 0.0157)</li>
<li>Increased COVID infection rate was also significantly associated with eviction rate in a county (p = 0.0178)</li>
<li>The linear model was a decent fit in this case</li>
</ul>
<p>A significant association does not imply causation, only correlation.</p>
<p>Indiana has recently moved into Stage 5 of its Back on Track reopening plan and should put serious consideration into how letting up restrictions can adversely and unfairly impact certain populations. In this case, African American Hoosiers and potential evictees are at an elevated risk of a faster COVID spread.</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<pre class="r"><code>DT::datatable(eviction_4)</code></pre>
<div id="htmlwidget-1" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83"],["18001","18003","18005","18007","18009","18011","18013","18015","18021","18023","18025","18027","18031","18033","18035","18037","18039","18041","18043","18045","18047","18049","18051","18053","18055","18057","18059","18061","18065","18067","18069","18073","18075","18079","18081","18083","18085","18087","18089","18091","18095","18097","18099","18101","18103","18105","18107","18109","18111","18113","18115","18117","18119","18121","18123","18125","18127","18129","18131","18135","18137","18139","18141","18143","18145","18147","18149","18151","18153","18155","18157","18159","18161","18163","18167","18169","18171","18173","18175","18177","18179","18181","18183"],[3.56881466086569e-05,8.85061707487402e-05,7.55838392395598e-05,5.46607916604068e-05,4.49920383343306e-05,8.25688847421542e-05,3.4479913232112e-05,7.2857980710325e-05,5.3906314842829e-05,0.000101165466345452,4.35340085909716e-05,9.59285875767085e-05,7.91919375702654e-05,5.48954679427961e-05,7.3380370827075e-05,0.00012597574757043,0.00018284421149767,8.49865384271313e-05,8.72322054914253e-05,3.65401596864441e-05,6.36882889506089e-05,6.17281085154699e-05,7.18059368545821e-05,6.48663299625114e-05,6.35598895081354e-05,7.9186622942674e-05,6.56818994377872e-05,7.03623069235015e-05,8.14609942130908e-05,8.21644926535684e-05,3.20011753653591e-05,6.03985360014173e-05,4.13174467695874e-05,5.53600850338775e-05,7.9757820753989e-05,6.00152987842252e-05,8.81347215990286e-05,0.000102874696581467,0.000112247831088799,6.60864867162742e-05,5.92561426526366e-05,0.000114476656899256,0.00012360229492533,7.01306414095051e-05,5.82668933340314e-05,7.24508598023618e-05,6.88558806654636e-05,4.99722107248573e-05,5.90533929575034e-05,0.000106200966477792,7.06943677999852e-05,6.96658219494275e-05,3.87678462774618e-05,2.92204404063684e-05,6.62684855629377e-05,5.90491102485192e-05,6.4820379181926e-05,6.41648676235202e-05,4.54865086536668e-05,4.307807794658e-05,4.77788582504996e-05,4.34930628165244e-05,0.00011967729849412,8.31260482482485e-05,7.95597060807676e-05,5.67909063400993e-05,5.95234374232714e-05,5.4362155201478e-05,7.71043044353531e-05,3.37129062802074e-05,6.4640449678503e-05,7.28588052791702e-05,5.16271195498692e-05,9.85744746188659e-05,7.75670363357771e-05,4.17053585346038e-05,2.3602665198654e-05,9.46896075114194e-05,4.53620365645495e-05,5.47469469699176e-05,4.90581387236406e-05,0.000107817400833895,4.1642548912914e-05],[545,682,818,680,593,796,932,667,653,680,533,609,739,657,691,605,719,648,723,639,649,616,658,650,582,1016,832,669,626,646,672,733,576,696,849,623,714,665,819,702,702,788,674,521,651,836,654,754,699,640,671,580,678,579,608,620,862,666,681,580,678,630,719,735,711,587,679,674,661,785,795,696,650,716,688,640,753,771,622,623,621,681,624],[0.7,11.34,1.99,0.83,0.58,1.24,0.33,0.34,0.24,0.72,0.1,1.41,0.56,0.12,5.76,0.39,5.58,2,4.87,0.44,0.24,0.99,1.64,6.56,0.21,3.53,1.99,0.81,1.73,6.94,0.71,0.72,0.58,1.43,1.88,2.96,0.71,0.05,24.38,10.81,7.75,26.84,0.57,0.29,5.04,2.86,0.85,0.37,0.28,0.48,0.96,1.4,0.61,2.03,3.05,0.19,3.17,1.33,0.28,0.37,0.48,0.87,12.75,0.25,1.26,0.59,0.67,0.25,4.5,0.99,4.39,0.15,0.16,9.04,6.07,0.83,0.56,1.55,0.1,4.7,0.56,0.36,0.36],[1.03,7.09,2.15,2.1,3.31,3.71,1.05,2.51,0.91,5.74,0,0.46,0.56,8.22,1.48,0.41,6.92,2.46,0.56,0.47,0,2.92,0.17,6.39,1.27,2.01,1.22,1.07,1.27,7.64,3.29,2.76,3.12,1.53,2.62,1.3,2.85,2.53,4.12,3.34,2.11,7.3,1.86,0.22,5.77,0.63,3.99,3.93,1.53,3.76,0,0.56,1.13,0.07,0,0,2.01,0.55,1.16,0.54,1.02,0.21,5.08,0.34,1.5,0,1.67,3.02,1.27,0.27,4.64,2.71,0.35,0.42,1.21,1.88,0.56,0.19,0.04,1.55,1.38,2.84,3.68],[21.63,31.15,29.26,29.25,25.84,24.11,20.56,19.48,24.78,27.56,20.75,27.64,29.76,23.09,36.17,24.26,30.5,31.14,27.62,25.29,20.08,23.06,22.71,30.31,20.93,21.66,21.76,18.48,26.54,31.04,24.22,22.42,25.16,24.25,29.16,33.99,23.5,18.82,31.14,29.44,30.94,45.73,23.12,22.07,27.03,46.37,28.96,23.64,24.79,24.91,21.31,23.73,20.36,20.17,20.41,17.98,23.02,16.86,23.44,26.32,22.75,28.57,31.53,27.51,27.7,17.79,18.96,22.45,26.84,28.54,47.21,22.18,28.05,36.73,39.24,25.89,19.46,18.3,23.28,31.55,18.83,22.62,17.64]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>county<\/th>\n      <th>avg_rate<\/th>\n      <th>median_gross_rent<\/th>\n      <th>pct_af_am<\/th>\n      <th>eviction_rate<\/th>\n      <th>pct_renter_occupied<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[2,3,4,5,6]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="session-info" class="section level2">
<h2>Session Info</h2>
<pre class="r"><code>devtools::session_info()</code></pre>
<pre><code>## - Session info ---------------------------------------------------------------
##  setting  value                       
##  version  R version 4.0.2 (2020-06-22)
##  os       Windows 10 x64              
##  system   x86_64, mingw32             
##  ui       RTerm                       
##  language (EN)                        
##  collate  English_United States.1252  
##  ctype    English_United States.1252  
##  tz       America/Indianapolis        
##  date     2020-10-09                  
## 
## - Packages -------------------------------------------------------------------
##  package     * version date       lib source        
##  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
##  backports     1.1.7   2020-05-13 [1] CRAN (R 4.0.0)
##  blob          1.2.1   2020-01-20 [1] CRAN (R 4.0.2)
##  blogdown      0.20    2020-06-23 [1] CRAN (R 4.0.2)
##  bookdown      0.20    2020-06-23 [1] CRAN (R 4.0.2)
##  broom         0.7.0   2020-07-09 [1] CRAN (R 4.0.2)
##  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.2)
##  cellranger    1.1.0   2016-07-27 [1] CRAN (R 4.0.2)
##  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)
##  colorspace    1.4-1   2019-03-18 [1] CRAN (R 4.0.2)
##  corrplot    * 0.84    2017-10-16 [1] CRAN (R 4.0.2)
##  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
##  crosstalk     1.1.0.1 2020-03-13 [1] CRAN (R 4.0.2)
##  curl          4.3     2019-12-02 [1] CRAN (R 4.0.2)
##  DBI           1.1.0   2019-12-15 [1] CRAN (R 4.0.2)
##  dbplyr        1.4.4   2020-05-27 [1] CRAN (R 4.0.2)
##  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
##  devtools    * 2.3.1   2020-07-21 [1] CRAN (R 4.0.2)
##  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.2)
##  dplyr       * 1.0.2   2020-08-18 [1] CRAN (R 4.0.2)
##  DT            0.15    2020-08-05 [1] CRAN (R 4.0.2)
##  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
##  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.2)
##  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
##  farver        2.0.3   2020-01-16 [1] CRAN (R 4.0.2)
##  forcats     * 0.5.0   2020-03-01 [1] CRAN (R 4.0.2)
##  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
##  generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.2)
##  ggplot2     * 3.3.2   2020-06-19 [1] CRAN (R 4.0.2)
##  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.2)
##  gridExtra     2.3     2017-09-09 [1] CRAN (R 4.0.2)
##  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
##  haven         2.3.1   2020-06-01 [1] CRAN (R 4.0.2)
##  hms           0.5.3   2020-01-08 [1] CRAN (R 4.0.2)
##  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
##  htmlwidgets   1.5.1   2019-10-08 [1] CRAN (R 4.0.2)
##  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
##  janitor       2.0.1   2020-04-12 [1] CRAN (R 4.0.2)
##  jsonlite      1.7.0   2020-06-25 [1] CRAN (R 4.0.2)
##  knitr         1.29    2020-06-23 [1] CRAN (R 4.0.2)
##  labeling      0.3     2014-08-23 [1] CRAN (R 4.0.0)
##  lattice       0.20-41 2020-04-02 [2] CRAN (R 4.0.2)
##  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
##  lubridate     1.7.9   2020-06-08 [1] CRAN (R 4.0.2)
##  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
##  Matrix        1.2-18  2019-11-27 [2] CRAN (R 4.0.2)
##  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.2)
##  modelr        0.1.8   2020-05-19 [1] CRAN (R 4.0.2)
##  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
##  pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.2)
##  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
##  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
##  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
##  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
##  processx      3.4.3   2020-07-05 [1] CRAN (R 4.0.2)
##  ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.2)
##  purrr       * 0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
##  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)
##  rappdirs      0.3.1   2016-03-28 [1] CRAN (R 4.0.2)
##  Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
##  readr       * 1.3.1   2018-12-21 [1] CRAN (R 4.0.2)
##  readxl        1.3.1   2019-03-13 [1] CRAN (R 4.0.2)
##  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
##  reprex        0.3.0   2019-05-16 [1] CRAN (R 4.0.2)
##  reticulate    1.16    2020-05-27 [1] CRAN (R 4.0.2)
##  rlang         0.4.7   2020-07-09 [1] CRAN (R 4.0.2)
##  rmarkdown     2.3     2020-06-18 [1] CRAN (R 4.0.2)
##  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)
##  rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.2)
##  rvest         0.3.6   2020-07-25 [1] CRAN (R 4.0.2)
##  scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
##  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
##  snakecase     0.11.0  2019-05-25 [1] CRAN (R 4.0.2)
##  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
##  stringr     * 1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
##  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.2)
##  tibble      * 3.0.3   2020-07-10 [1] CRAN (R 4.0.2)
##  tidyr       * 1.1.1   2020-07-31 [1] CRAN (R 4.0.2)
##  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.2)
##  tidyverse   * 1.3.0   2019-11-21 [1] CRAN (R 4.0.2)
##  usethis     * 1.6.1   2020-04-29 [1] CRAN (R 4.0.2)
##  vctrs         0.3.2   2020-07-15 [1] CRAN (R 4.0.2)
##  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.2)
##  xfun          0.16    2020-07-24 [1] CRAN (R 4.0.2)
##  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.2)
##  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
## 
## [1] C:/Users/Jack/Documents/R/win-library/4.0
## [2] C:/Program Files/R/R-4.0.2/library</code></pre>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

