---
title: "Tidy Tuesday 01-11-2021: Art Collections"
description: "Tidy Tuesday 2021, Week 2"
date: 2021-01-11
categories: ["R"]
tags: ["R", "R markdown", "Tidy Tuesday", "Tidyverse"]
twitterImg: images/clip.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

## Downloading Data

```{r}
tt <- tidytuesdayR::tt_load(2021, week = 3)
artists <- tt$artists
artwork <- tt$artwork

library(tidyverse)

artwork %>%
    select(id, medium, year, width, height) %>%
    drop_na %>%
    mutate(
        top = height/2,
        bottom = -top,
        right = width/2,
        left = -right
    ) ->
    artwork_2
```

```{r, out.height=800, out.width=800}
low <- min(artwork_2$left)*0.5
high <- max(artwork_2$right)*0.5

ggplot(artwork_2) +
    xlim(0, high) +
    ylim(0, high) +
    geom_segment(aes(x = right, xend = right, y = 0, yend = top), 
                 artwork_2, alpha=0.05, color="#947a27") + 

    geom_segment(aes(x = 0, xend = right, y = top, yend = top), 
                 artwork_2, alpha=0.05, color="#d4af37") +
    
    geom_segment(aes(x = high - right, xend = high - right, y = high, yend = high - top), 
                 artwork_2, alpha=0.05, color="#947a27") + 
    
    geom_segment(aes(x = high, xend = high - right, y = high - top, yend = high - top), 
                 artwork_2, alpha=0.05, color="#d4af37") +
    
    theme_void() +
    theme(
        plot.background = element_rect(fill="black"),
        plot.caption = element_text(color="#aa8c2c")
    ) + 
    labs(caption = "Generated Using Width and Height Data From The Tate Collection (https://github.com/tategallery/collection)")
```

